name: Deploy Node.js Proxmox Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to custom port
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          port: 2222
          script: |
            # 必要ならクローン
            if [ ! -d ~/MONITORING-API/.git ]; then
              rm -rf ~/MONITORING-API
              git clone git@github.com:ganon-test/monitoring-tool.git ~/MONITORING-API || exit 1
            fi

            cd ~/MONITORING-API
            git pull origin main || exit 1

            # Node.js依存関係のインストール（package.jsonがある場合）
            if [ -f package.json ]; then
              npm install || exit 1
            fi

            # Node.js dashboard依存関係のインストール
            cd nodejs-dashboard
            npm install || exit 1

            # screen コマンドの存在確認＆インストール
            command -v screen >/dev/null 2>&1 || apt install -y screen

            # 既存のscreenセッションを停止
            screen -S monitoring-api -X quit || true
            screen -S monitoring-node -X quit || true
            screen -S proxmox-dashboard -X quit || true

            # Node.js Proxmox Dashboard（新しいシステム）
            screen -dmS proxmox-dashboard bash -c "
              export NEXTCLOUD_PASSWORD='${{ secrets.NEXTCLOUD_PASSWORD }}';
              export PROXMOX_PASSWORD_1='${{ secrets.PROXMOX_PASSWORD_1 }}';
              export PROXMOX_PASSWORD_2='${{ secrets.PROXMOX_PASSWORD_2 }}';
              cd ~/MONITORING-API/nodejs-dashboard && node app.js
            "
