name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to custom port
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          port: 2222
          script: |
            # 必要ならクローン
            if [ ! -d ~/MONITORING-API ]; then
            git clone git@github.com:YOUR_USER/YOUR_REPO.git ~/MONITORING-API
            fi

            cd ~/MONITORING-API
            git pull origin main

            # Flask 起動
            command -v screen >/dev/null 2>&1 || apt install -y screen
            screen -S api -X quit || true
            screen -dmS api python3 main.py

            # Node.js 側
            cd monitor
            [ -f package.json ] && npm install
            screen -S monitor -X quit || true
            screen -dmS monitor node server.js

