name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to custom port
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          port: 2222
          script: |
            # 必要ならクローン
            if [ ! -d ~/MONITORING-API/.git ]; then
              rm -rf ~/MONITORING-API
              git clone git@github.com:ganon-test/monitoring-tool.git ~/MONITORING-API || exit 1
            fi

            cd ~/MONITORING-API
            git pull origin main || exit 1

            # screen コマンドの存在確認＆インストール
            command -v screen >/dev/null 2>&1 || apt install -y screen

            # Flask API
            screen -S monitoring-api -X quit || true
            screen -dmS monitoring-api bash -c 'cd ~/MONITORING-API && python3 main.py'

            # Node.js monitor
            if [ -d ~/MONITORING-API/monitor ]; then
              screen -S monitoring-node -X quit || true
              screen -dmS monitoring-node bash -c 'cd ~/MONITORING-API/monitor && npm install && node server.js'
            fi
